name: advent-of-code-y2024
version: 0.1.0.0
github: "ehofreiter/advent-of-code"
license: BSD3
author: "Eric W. Hofreiter"
copyright: "2024 Eric W. Hofreiter"

extra-source-files:
  - README.md

description: Please see the README on GitHub.

language: GHC2021

default-extensions:
  - OverloadedStrings
  - LambdaCase

dependencies:
  - attoparsec
  - base >= 4.7 && < 5
  - bytestring
  - containers
  - filepath
  - indexed-traversable
  - lens
  - linear
  - mtl
  - parsec
  - split
  - text
  - vector

library:
  source-dirs: src

executables:
  advent-of-code-y2024-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - advent-of-code-y2024
